### ISSUE TITLE
YAMLLoadWarning

### ISSUE THREAD

**Issue by garrett-aviso** [evilgeniuslabs/pycarbon#5]
> site-packages/pycarbon/configuration.py:22: YAMLLoadWarning: calling yaml.load_all() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.

Pretty much just need to add a Loader=yaml.FullLoader to get rid of this error message.

A more complex fix is of course to allow the desired loader to be passed in, but the above is quick and works if you author your own config files.  ;)

**Comment by mbelles** [comment]
Fixed in v1.0.7. I'm also moving this repository over to a different github org: https://github.com/443labs/pycarbon
